export enum Items {
  BATHTUB = 'Bathtub',
  BIDET = 'Bidet',
  CLOTHES_WASHER = 'Clothes Washer',
  DOMESTIC_DISHWASHER = 'Domestic Dishwasher',
  CUSPIDOR = 'Cuspidor',
  DRINKING_FOUNTAIN = 'Drinking Fountain',
  LAVATORY = 'Lavatory',
  HOSE_BIBB = 'Hose Bibb',
  LAWN_SPRINKLER = 'Lawn Sprinkler',
  BAR_SINK = 'Bar Sink',
  CLINICAL_FAUCET = 'Clinical Faucet',
  DOMESTIC_KITCHEN_SINK = 'Domestic Kitchen Sink',
  LAUNDRY_SINK = 'Laundry Sink',
  SERVICE_MOP_BASIN = 'Service Mop Basin',
  SHOWER_HEAD = 'Shower Head',
  FLUSHOMETER_VALVE_WITH_ONE_GPF = 'Flushometer Valve with 1.0 GPF',
  FLUSHOMETER_VALVE_WITH_GREATER_THAN_ONE_GPF = 'Flushometer Valve with greater than 1.0 GPF',
  FLUSH_TANK = 'Flush Tank',
  WATER_CLOSET_WITH_ONE_POINT_SIX_GPF = 'Water Closet with 1.6 GPF',
  FLUSHOMETER_TANK_WITH_ONE_POINT_SIX_GPF = 'Flushometer Tank with 1.6 GPF',
  FLUSHOMETER_VALVE_WITH_ONE_POINT_SIX_GPF = 'Flushometer Valve with 1.6 GPF',
  GRAVITY_TANK_WITH_ONE_POINT_SIX_GPF = 'Gravity Tank with 1.6 GPF',
  WATER_CLOSET_WITH_GREATER_THAN_ONE_POINT_SIX_GPF = 'Water Closet with greater than 1.6 GPF',
  FLUSHOMETER_VALVE_WITH_GREATER_THAN_ONE_POINT_SIX_GPF = 'Flushometer Valve with greater than 1.6 GPF',
  GRAVITY_TANK_WITH_GREATER_THAN_ONE_POINT_SIX_GPF = 'Gravity Tank with greater than 1.6 GPF',
}
